### ISSUE TITLE
Create an Profile site

### ISSUE THREAD

**Issue by Johannafendrich** [Johannafendrich/my-homie#41]
As a user, I want a profile site to insert all important pieces of information about myself.

**Tasks** 

- [x]  build a header section
- [x]  build a profile image section
- [x]  build an information section
- [x]  build a form section
- [ ]  save data to db
